### ISSUE TITLE
Trough object incompatible with `adjust_wells_liquids`

### ISSUE THREAD

**Issue by tianar** [PyLabRobot/pylabrobot#34]
I modified the simulation tutorial to assign a reservoir plate (`VWRReagentReservoirs25mL`) to the plate carrier. However, when adding liquid to it with the new function 
```
await sb.adjust_wells_liquids(lh.get_resource("plate_04"), liquids=[(None, 1000)])
```
I get the error:
```
File ~/Documents/Code/pylabrobot/pylabrobot/liquid_handling/backends/simulation/simulator_backend.py:194, in SimulatorBackend.adjust_wells_liquids(self, plate, liquids)
    180 """ Fill all wells in a plate with the same mix of liquids (**simulator only**).
    181 
    182 Simulator method to fill a resource with liquid, for testing of liquid handling.
   (...)
    189     left and going down, then right.
    190 """
    192 serialized_pattern = []
--> 194 if len(liquids) != plate.num_items:
    195   raise ValueError("The number of wells in the plate does not match the number of liquids.")
    197 for well, well_liquids in zip(plate.get_all_items(), liquids):

AttributeError: 'Trough' object has no attribute 'num_items'
```

**Comment by rickwierenga** [comment]
Sorry for the late response...

Troughs weren't supported in the simulator. Fixed by: https://github.com/PyLabRobot/pylabrobot/commit/662dd528f6d91457b448a961e9b4cac311d2539c

You can edit the liquid in troughs with `adjust_container_liquids`: https://github.com/PyLabRobot/pylabrobot/commit/69d47aa88cfc22c4668cdd56a9221dd0abac24e3

Thank you for reporting this!
